# This is a basic workflow to help you get started with Actions

name: Debug

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  androidBuild:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: true

      - name: Setup Android NDK
        id: setup-ndk
        uses: nttld/setup-ndk@main
        with:
          ndk-version: r21e

      - name: Setup Java JDK
        uses: actions/setup-java@main
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5

      - name: Restore Previous Cache
        id: cache-build-android-restore
        uses: actions/cache/restore@main
        with:
          path: |
            .haxelib/
            Export/android/haxe/
            Export/android/obj/
          key: cache-build-android

      - name: Installing Libraries
        run: |
          haxelib --quiet install hxcpp
          haxelib --quiet install lime
          haxelib --quiet git extension-androidtools https://github.com/MAJigsaw77/extension-androidtools.git
          haxelib --quiet git hxlua https://github.com/MAJigsaw77/hxlua.git
          haxelib list

      - name: Configure Android
        run: |
          haxelib run lime setup -alias -y
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Building
        run: haxelib run lime build android -debug

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: androidBuild
          path: Export/android/bin/app/build/outputs/apk/debug
          if-no-files-found: error

      - name: Clear Previous Cache
        uses: actions/github-script@main
        with:
          script: |
            const caches = await github.rest.actions.getActionsCacheList({
            	owner: context.repo.owner,
            	repo: context.repo.repo,
            })

            if (typeof caches.data.actions_caches != null && caches.data.actions_caches.length > 0) {
            	for (const cache of caches.data.actions_caches) {
            		if (cache.key == "cache-build-android") {
            			console.log('Clearing ' + cache.key + '...')
            			await github.rest.actions.deleteActionsCacheById({
            				owner: context.repo.owner,
            				repo: context.repo.repo,
            				cache_id: cache.id,
            			})
            			console.log("Previous Cache Cleared!")
            		}
            	}
            }

      - name: Save Current Cache
        id: cache-build-android-save
        uses: actions/cache/save@main
        with:
          path: |
            .haxelib/
            Export/android/haxe/
            Export/android/obj/
          key: cache-build-android
